language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: RLVyaeUTh9hd1VZ9+ZgOUwOT/CbfqZePKM4KLzCdsHyqL5gD7OSRonjEn24x7UdvWY2EUEdq0A3N5PSmf+rlc85vm9QtkGeIAttcMnv8yE0mO8bJDkzKAdr0dZJ2QImWcVeZoM0DLGO0RoUVwQKIuuQiXkI3iXO3Dv3gQhxaTPdQmqQ/GKuP/BGaD7PdvJOrWICYhSTvsA3/vvm608t70UTpsaRc93C4/DiH0qW+7pauSOcKvRzkWSv3PwL85XbFkz/gKPao2+iE+nbAaVc68X5z7YiYSCRy7WdyeTJ1mM5tYpyyiySc+u+vDMfkYp8PEUsxDqbLBSEhOHy4jJnIxTQHuOFULogjKx/brbo5U9VSL/WoZkiCbTyRe1+AyVX7+EM/HqWm7BqGotvENEgiOQSbb4GrAoDYQ5RYXzlAV6cqUHsJx3pzKcQzfztZCwGaKjS4pTQmX8BkH7yGH8W8x2GwYIG9wz3UO75s+wzRwcj92fjSkncjGumSqe7Fjb58cv85jkqkuTEM+aIe9d7XL4wRHT06pXSxY7JIzJI4MFLU60fsrxDD8540tJRxNYrSqDM5svLIA+le01M4Mi2weu+UoFVXA8rN1bsjWTL6uTHzIgOLkrje8h/77Ej0zPalW79ege6LjDsWClijxPEbIB6yI0DLX0Bw7POXltFr5tI=
  on:
    branch: master
before_script:
  - "yarn global add gatsby"
after_success:
  - "yarn build"
